---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    run_list:
      - recipe[ubuntu::default]

suites:
  - name: default
    run_list:
      - recipe[harbor::default]
    attributes:
